# TODO implement the kubernetes manifest here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: BotApp
spec:
  selector:
    matchLabels:
      app: BotApp
      replicas: 3
  template:
    metadata:
      labels:
        app: BotApp
    spec:
      containers:
      - name: BotApp
        image: 700935310038.dkr.ecr.us-west-2.amazonaws.com/matan-dev-bot:latest
        ports:
        - containerPort: 80