apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-app
  template:
    metadata:
      labels:
        app: bot-app
        env: env_to_replace
    spec:
      containers:
      - name: bot-app
        image: dynamic_image
        env:
          - name: ENV
            value: env_to_replace
