# TODO implement the kubernetes manifest here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: BotApp
spec:
  selector:
    matchLabels:
      app: BotApp
      replicas: 1
  template:
    metadata:
      labels:
        app: BotApp
        env: env_to_replace
    spec:
      containers:
      - name: BotApp
        image: dynamic_image
